# Generated by Django 4.2 on 2023-05-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Oder_Item',
            new_name='Order_Item',
        ),
    ]
