# Generated by Django 4.2 on 2023-05-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oder_item_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='oder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='oder',
            new_name='order',
        ),
    ]
