# Generated by Django 4.2 on 2023-05-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_date_oder_order_date_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='Orderitem',
        ),
    ]
